### ISSUE TITLE
对https的图片不支持

### ISSUE THREAD

**Issue by loubobooo** [anbai-inc/ab-editor#1]
如题：对https的图片不支持，希望优化

**Comment by anbai-inc** [comment]
请问你说的是上传那里？上传成功后返回的是相对的[url地址](https://github.com/anbai-inc/ab-editor/blob/3d6276c59579bcf52e0d658887a9f70d5120ddf0/src/main/java/com/anbai/editor/api/ABEditorAPI.java#L299)应该没问题。
图片直接引用https地址测试也没问题，麻烦说下是哪里发现有问题？

**Comment by loubobooo** [comment]
1.是直接引用https的图片地址，不展示图片。
2.上传走的是http，显示正常的。

**Comment by anbai-inc** [comment]
![1](https://user-images.githubusercontent.com/34703277/36660517-5c567cc2-1b13-11e8-8192-0ffa4f4734b4.png)
如图,测试插入腾讯和百度的https图片是正常的，这里的插入其实只是把md的语法解析成了html的标签，严格来说和是不是https没关系。建议你检查下你的https证书是不是不受浏览器信任导致的？
